from __future__ import annotations

import os
import re
import shlex
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Dict, List, Optional

APP_NAME = "SHTUClaudeProxy"


def is_windows() -> bool:
    return sys.platform.startswith("win")


def is_macos() -> bool:
    return sys.platform == "darwin"


def default_claude_settings_path() -> str:
    return str(Path.home() / ".claude" / "settings.json")


def default_codex_config_path() -> str:
    return str(Path.home() / ".codex" / "config.toml")


def default_codex_auth_path() -> str:
    return str(Path.home() / ".codex" / "auth.json")


def default_claude_path() -> str:
    candidates = ["claude.cmd", "claude.exe", "claude"] if is_windows() else ["claude"]
    for candidate in candidates:
        found = shutil.which(candidate)
        if found:
            return found
    if is_windows():
        appdata = os.getenv("APPDATA")
        if appdata:
            return str(Path(appdata) / "npm" / "claude.cmd")
    return "claude"


def path_has_other_user_home(value: str) -> bool:
    if not value:
        return False
    if not is_windows() and re.match(r"^[A-Za-z]:[\\/]Users[\\/]", value):
        return True
    try:
        candidate = Path(os.path.expandvars(value)).expanduser()
        home = Path.home()
        return candidate.is_absolute() and "Users" in candidate.parts and home not in (candidate, *candidate.parents)
    except Exception:
        return False


def portable_claude_path(value: str) -> str:
    value = (value or "").strip()
    if not value or path_has_other_user_home(value):
        return default_claude_path()
    expanded = os.path.expandvars(value)
    if expanded != value:
        return expanded
    candidate = Path(value).expanduser()
    if candidate.is_absolute() and not candidate.exists() and "node_modules" not in value:
        found = default_claude_path()
        return found or value
    return value


def portable_settings_path(value: str) -> str:
    value = (value or "").strip()
    if not value or path_has_other_user_home(value):
        return default_claude_settings_path()
    return os.path.expandvars(value)


def portable_codex_config_path(value: str) -> str:
    value = (value or "").strip()
    if not value or path_has_other_user_home(value):
        return default_codex_config_path()
    return os.path.expandvars(value)


def portable_codex_auth_path(value: str) -> str:
    value = (value or "").strip()
    if not value or path_has_other_user_home(value):
        return default_codex_auth_path()
    return os.path.expandvars(value)


def app_dir() -> Path:
    if getattr(sys, "frozen", False):
        if is_windows():
            base = os.getenv("APPDATA") or str(Path.home() / "AppData" / "Roaming")
            return Path(base) / APP_NAME
        if is_macos():
            return Path.home() / "Library" / "Application Support" / APP_NAME
        xdg_config = os.getenv("XDG_CONFIG_HOME")
        return (Path(xdg_config) if xdg_config else Path.home() / ".config") / APP_NAME
    return Path(__file__).resolve().parent


def shell_script_text(env: Dict[str, str], claude_path: str) -> str:
    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "# Generated by SHTUClaudeProxy",
    ]
    for key, value in env.items():
        lines.append(f"export {key}={shlex.quote(value)}")
    command = shlex.quote(claude_path or "claude")
    lines.extend([
        "echo 'SHTUClaudeProxy config loaded.'",
        "echo \"ANTHROPIC_BASE_URL=$ANTHROPIC_BASE_URL\"",
        "echo \"ANTHROPIC_MODEL=$ANTHROPIC_MODEL\"",
        f"exec {command} \"$@\"",
    ])
    return "\n".join(lines) + "\n"


def powershell_script_text(env: Dict[str, str], claude_path: str) -> str:
    lines = [
        "$ErrorActionPreference = \"Stop\"",
        "# Generated by SHTUClaudeProxy",
    ]
    for key, value in env.items():
        escaped = value.replace("'", "''")
        lines.append(f"$env:{key} = '{escaped}'")
    command = (claude_path or "claude").replace("'", "''")
    lines.extend([
        "Write-Host 'SHTUClaudeProxy config loaded.' -ForegroundColor Green",
        "Write-Host \"ANTHROPIC_BASE_URL=$env:ANTHROPIC_BASE_URL\"",
        "Write-Host \"ANTHROPIC_MODEL=$env:ANTHROPIC_MODEL\"",
        f"& '{command}' @args",
    ])
    return "\n".join(lines) + "\n"


def launch_script_filename() -> str:
    return "claude-shtu.ps1" if is_windows() else "claude-shtu.sh"


def launch_script_text(env: Dict[str, str], claude_path: str) -> str:
    if is_windows():
        return powershell_script_text(env, claude_path)
    return shell_script_text(env, claude_path)


def launch_claude(claude_path: str, env_values: Dict[str, str]) -> subprocess.Popen:
    env = os.environ.copy()
    env.update(env_values)
    command = claude_path or "claude"
    if is_windows():
        flags = subprocess.CREATE_NEW_CONSOLE if hasattr(subprocess, "CREATE_NEW_CONSOLE") else 0
        quoted = command.replace("'", "''")
        return subprocess.Popen(
            ["powershell.exe", "-NoExit", "-Command", f"& '{quoted}'"],
            env=env,
            cwd=str(Path.home()),
            creationflags=flags,
        )
    if is_macos() and os.getenv("DISPLAY") is None:
        script = "cd $HOME; " + " ".join(f"export {k}={shlex.quote(v)};" for k, v in env_values.items()) + f" exec {shlex.quote(command)}"
        escaped_script = script.replace("\\", "\\\\").replace('"', '\\"')
        return subprocess.Popen([
            "osascript",
            "-e",
            f'tell application "Terminal" to do script "{escaped_script}"',
        ], env=env, cwd=str(Path.home()))
    terminal = shutil.which("x-terminal-emulator") or shutil.which("gnome-terminal") or shutil.which("konsole") or shutil.which("xterm")
    if terminal and os.getenv("DISPLAY"):
        if Path(terminal).name == "gnome-terminal":
            return subprocess.Popen([terminal, "--", command], env=env, cwd=str(Path.home()))
        return subprocess.Popen([terminal, "-e", command], env=env, cwd=str(Path.home()))
    return subprocess.Popen([command], env=env, cwd=str(Path.home()))
